version: '3.8'

services:
  web:
    image: projects-portfolio-web
    container_name: nextjs-app
    ports:
      - '80:80'
    depends_on:
      - api
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 80
      NEXT_PUBLIC_API_URL: 'http://api:4000' # <-- use "api" here

  api:
    image: projects-portfolio-api
    container_name: api
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/mydb'
      # Optional: point your application to the volume path for uploads
      IMAGES_UPLOAD_PATH: '/usr/src/app/uploads'
    volumes:
      # Mount the named volume into the container at /usr/src/app/uploads
      - api_images:/usr/src/app/uploads

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  api_images:
