version: '3.8'

services:
  nextjs-app:
    image: projects-portfolio-web
    container_name: nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: 'http://localhost:4000'

  api:
    image: projects-portfolio-api
    container_name: api
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/mydb'

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
