version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:23.6.0
      
jobs:
  build:
    executor: node-executor
    steps:
      - checkout # Clone the repository

      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install pnpm package manager
          command: sudo npm install -g pnpm

      - run:
          name: Install Dependencies
          command: pnpm install

      - save_cache: # Cache pnpm dependencies
          paths:
            - ~/.pnpm-store
          key: v1-pnpm-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Build Workspace
          command: "npx nx run-many -t build"

workflows:
  version: 2
  build:
    jobs:
      - build
