import { getServerSession } from 'next-auth';
import { ToastContainer } from 'react-toastify';
import { Navbar } from '../components/Navbar';
import { Providers } from '../components/Providers';
import './global.css';

export const metadata = {
  title: 'Welcome to public-web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <ToastContainer />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
