import { Navbar } from '../components/Navbar';
import './global.css';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'Welcome to public-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
